from enum import Enum


class UserRole(str, Enum):
    APPLICANT = "APPLICANT"
    OFFICER = "OFFICER"
    COMMITTEE = "COMMITTEE"
    ADMIN = "ADMIN"


class ApplicationStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_AI_VERIFICATION = "UNDER_AI_VERIFICATION"
    DEFICIENT = "DEFICIENT"
    RESUBMITTED = "RESUBMITTED"
    UNDER_MANUAL_REVIEW = "UNDER_MANUAL_REVIEW"
    VERIFIED = "VERIFIED"
    SHORTLISTED = "SHORTLISTED"
    MERIT_RANKED = "MERIT_RANKED"
    SELECTED = "SELECTED"
    WAITLISTED = "WAITLISTED"
    REJECTED = "REJECTED"
    FELLOWSHIP_ACTIVE = "FELLOWSHIP_ACTIVE"


class DocumentStatus(str, Enum):
    PENDING = "PENDING"
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    VERIFIED = "VERIFIED"
    FLAGGED = "FLAGGED"
    REJECTED = "REJECTED"
    RESUBMISSION_REQUIRED = "RESUBMISSION_REQUIRED"


class NotificationChannel(str, Enum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    SMS = "SMS"


class SelectionResultEnum(str, Enum):
    SELECTED = "SELECTED"
    WAITLISTED = "WAITLISTED"
    REJECTED = "REJECTED"


class AuditEntityType(str, Enum):
    APPLICATION = "APPLICATION"
    DOCUMENT = "DOCUMENT"
    USER = "USER"
    SCHEME = "SCHEME"
    FELLOWSHIP = "FELLOWSHIP"
    DISBURSEMENT = "DISBURSEMENT"
    DEFICIENCY = "DEFICIENCY"
    COMMITTEE = "COMMITTEE"
    SELECTION = "SELECTION"
    SYSTEM = "SYSTEM"


class FellowshipStatus(str, Enum):
    ACTIVE = "ACTIVE"
    UNDER_RENEWAL = "UNDER_RENEWAL"
    SUSPENDED = "SUSPENDED"
    COMPLETED = "COMPLETED"
    TERMINATED = "TERMINATED"


class DisbursementStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED_FOR_PAYMENT = "APPROVED_FOR_PAYMENT"
    PROCESSING = "PROCESSING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    RETRY_EXHAUSTED = "RETRY_EXHAUSTED"
    # Backwards compatibility
    PENDING = "PENDING"
    DISBURSED = "DISBURSED"
    SUSPENDED = "SUSPENDED"


class SubmissionStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEFICIENT = "DEFICIENT"
